### ISSUE TITLE
PromiseQueue, StackOverflow

### ISSUE THREAD

**Issue by simondaudin** [primeval-io/primeval-codex#9]
With this testcase, we get a StackOverflowError
```
@Test
    public void testStackOverflow() throws Exception {
        Deferred<Integer> deferred = new Deferred<>();
        AtomicInteger nbCalled = new AtomicInteger();
        PromiseQueue<Integer> promiseQueue = new PromiseQueue<>(c -> {
            int i = nbCalled.getAndIncrement();
            if (i == 0) {
                return deferred.getPromise();
            } else {
                return Promises.resolved(i);
            }
        }, 1, 0);
        List<Promise<Integer>> promises = Lists.newArrayList();
        for (int i = 0; i < 10000; i++) {
            int j = i;
            Promise<Integer> dispatch = promiseQueue.dispatch(() -> j);
            promises.add(dispatch);
        }
        deferred.resolve(0);
        Throwable failure = Promises.all(promises).getFailure();
    }
```

This is surely due to the chained callback of promises.

**Comment by magnet** [comment]
Hi, `PromiseQueue` is meant to be used with a `Dispatcher`, hence the `dispatcher` parameter name for the `Function<Callable<T>>`. Sorry, the documentation is not very explicit, I will fix that.

In the mean time you can have a look at the class `PromiseQueueTest`.

Because we're using a dispatch for all callbacks, the stack does not grow and the `StackOverflowException` will not happen (unless your code itself grows the stack too much).
